### ISSUE TITLE
Concatenate fasta headers problem

### ISSUE THREAD

**Issue by SebP-D** [abhijeetsingh1704/DupRemover#1]
Hi Abhi, 

I'm not sure if you still check this Github, but I have one problem. 

I have used your script multiple times before, and its usually fantastic as any duplicate will just increase the database search space and processing time

If there are a lot of duplicates in the .fasta file, then the concatenating nature of the script means that sometimes the header can be so long that it causes problems with downstream analyses (such as in the case of adding reversed sequences with programs like Philosopher). I had several common duplicate proteins from a compiled list of 40 organisms that made several headers over 10,000 characters long! 

Would it be possible to amend the script to make header concatenation optional? 

Thank you!

**Comment by abhijeetsingh1704** [comment]
Hi,
Sure I understand that problem.
The quick remedy is just to remove the duplicate names as they are not so useful in the downstream analyses.

Please use simple one liner as a fix

```
cut -d "|" -f1 input.fasta > output.fasta
```

In this way the header will have only first name of duplicate names and remove all others. 

Try if it works for you.
